#在这里改端口
server:
  port: 8082
spring:
  datasource:
    database1:
      url: jdbc:mysql://192.168.7.16:3306/mtload?useUnicode=true&characterEncoding=utf8
      username: root
      password: mtload
      driverClassName: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        #最大活跃数
        maxActive: 20
        #初始化数量
        initialSize: 1
        #最大连接等待超时时间
        maxWait: 60000
        #打开PSCache，并且指定每个连接PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
        #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1 from dual
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
        filters: stat,wall,slf4j
    database2:
      url: jdbc:mysql://192.168.7.11:3306/mtload?useUnicode=true&characterEncoding=utf8
      username: root
      password: mtload
      driverClassName: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        #最大活跃数
        maxActive: 20
        #初始化数量
        initialSize: 1
        #最大连接等待超时时间
        maxWait: 60000
        #打开PSCache，并且指定每个连接PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
        #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1 from dual
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
        filters: stat,wall,slf4j
  data:
    mongodb:
      database1:
        host: 192.168.7.16
        port: 27017
        username: mtload
        password: mtload
        database: mtloadpre
      database2:
        host: 192.168.7.11
        port: 27017
        database: mtloadpre
        username: mtload
        password: mtload
  redis:
    lettuce:
      pool:
        max-total: 50
        min-idle: 1
        max-wait-millis: 5000
        max-idle: 8
        test-on-borrow: true
        test-on-return: true
        test-while-idle: true
    # 明姐测试pre用这个redis配置
    redis1:
      port: 6379
      timeout: 5000
      database: 0
      hostName: 192.168.7.16
    redis2:
      port: 6379
      timeout: 5000
      database: 0
      hostName: 192.168.7.11

