spring:
  profiles:
    active: prod
  cache:
    ehcache:
      config: classpath:ehcache.xml
  security:
    http:
    basic:
      enabled: true
    user:
      name: mtload
      password: mtload
      role: USER      #认证角色
